services:
  mssql:
    container_name: mssql
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    expose:
      - "1433"
    networks:
      - app-network
    environment:
      - SA_PASSWORD=F0rmati0n!
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1433
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init:/init
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'F0rmati0n!' -Q 'SELECT 1' -C"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s

  db-init:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      - app-network
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./init:/init
    command: >
      bash -c "/opt/mssql-tools18/bin/sqlcmd -C -S mssql -U SA -P 'F0rmati0n!' -i /init/01-create-database.sql"

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql;databaseName=PASTRY;trustServerCertificate=true;encrypt=true;integratedSecurity=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=F0rmati0n!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network
    depends_on:
      db-init:
        condition: service_completed_successfully
    volumes:
      - .m2:/root/.m2

networks:
  app-network:

volumes:
  mssql-data: